### ISSUE TITLE
Books aren't opening on ios

### ISSUE THREAD

**Issue by mudasirkhan** [futurepress/epubjs-rn#47]
My app is running fine on android but books dont load on ios , instead it just shows a blank white screen.

**Comment by MustansirZia** [comment]
I had the same issue and the issue is because you're using an older version of `epubjs-rn`.
To fix it on iOS do the following steps: 

• Update `epubjs-rn` by running `yarn upgrade epubjs-rn` or `npm up epubjs-rn --save`
This should update your version to `0.0.96`.

• Now the reason why your version isn't working because the older version didn't have this forked repo by @fchasen [react-native-wkwebview](https://github.com/fchasen/react-native-wkwebview)
Once you've updated you should have this repo in your node_modules.
This repo has native iOS code so you need to link it your iOS app. 
Link it using the Alternative 1 described [here](https://github.com/fchasen/react-native-wkwebview). (Couldn't get automatic linking to work for this)
This should be all!

Hope it helps! :)

**Comment by mudasirkhan** [comment]
Thank You
