### ISSUE TITLE
Android Bug: onPress never fire (only onLongPress) 

### ISSUE THREAD

**Issue by imarem** [futurepress/epubjs-rn#58]
Hi @fchasen 

After upgrade the latest version, the onPress function doesn't fire, only fire onLongPress.

Does anyone have this behavior? 

I'm running on Android.

EDIT: @valinaga The onpress works correctly in your release?

Thanks.

**Comment by valinaga** [comment]
@imarem,  it does not manifest on my side and I'm on the latest version.

**Comment by vegmorse** [comment]
Hi @imarem 

I'm having the same issue after upgrade from v0.0.99 to latest (v0.0.103). Only apears in Android devices.

Since version 0.0.100, introduced functions related to the longpress, and I have the impression that there is where the issue.

@fchasen , does it work properly on android devices?

Thanks in advance.

**Comment by imarem** [comment]
Hi @vegmorse 

Exactly, it seems that on Android devices (Samsung S7 in my case), the functionality onPress, has stopped working. Debugging I could only trigger the onlongpress event.

The version v0.0.96 is the only one that works onPress fine.

**Comment by valinaga** [comment]
I start to see this too on last version. Actually I didn't pay attention on it since the code for press and long press was the same and I thought it was press. My bad. 
It's pretty annoying since the swipe fire onPress and this in bound to show the toolbar. So at every swipe the toolbar toggle. And there's no way to bind the toolbar toggle on longPress because it fires along with press.

**Comment by imarem** [comment]
Hi @valinaga 

On my project, I've disabled the functionality of onlongpress. I'd rather be able to display the toolbar (with chapters Modal, and some functionalities for theme and fontsize) than make bookmarks.

As a workaround, to disable the longpress, I have modified the value of e.changedTouches[0].force to 1.1, if you want to do this for the moment, go to the component Rendition.js, and search in the code rendered at the top for the value 0.8 and replace it with 1.1. and longpress never fire...

It's a shame that this stops working ... I Know...

**Comment by valinaga** [comment]
@imarem I really need to have the longpress since the press in triggered on swipe as well and toggle the toolbar. will wait for a fix. hopefully @fchasen will save the day again :)

**Comment by fchasen** [comment]
Working on this now, can you please test what force returns and the touch events on the devices you have available: https://jsfiddle.net/5a37p5jr/4/

**Comment by fchasen** [comment]
I've just disabled force touch for Android for now so this should be working again in `epubjs@0.0.106`

Still curious to see what a Samsung device returns for force.
